//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pruebaformularios
{
    using System;
    using System.Collections.Generic;
    
    public partial class Caja
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Caja()
        {
            this.Carpetas = new HashSet<Carpeta>();
        }
    
        public int ID { get; set; }
        public string CodigoBarras { get; set; }
        public Nullable<int> Zona { get; set; }
        public Nullable<int> Seccion { get; set; }
        public Nullable<int> Nivel { get; set; }
        public string Cara { get; set; }
        public Nullable<int> EntidadID { get; set; }
    
        public virtual EntidadFinanciera EntidadFinanciera { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Carpeta> Carpetas { get; set; }
    }
}
